<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ApsGenerator.Core\ApsGenerator.Core.csproj"
                      AdditionalProperties="TargetFramework=$(TargetFramework)" />
    <Compile Include="..\Compatibility\CompilerServicesPolyfills.cs" Link="Compatibility\CompilerServicesPolyfills.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.1</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('linux')) Or ('$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOsPlatform('Linux')))">
    <None Include="runtimes/linux-x64/native/*.so*" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup Condition="$(RuntimeIdentifier.StartsWith('win')) Or ('$(RuntimeIdentifier)' == '' And $([MSBuild]::IsOsPlatform('Windows')))">
    <None Include="runtimes/win-x64/native/*.dll" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
